# Generated by Django 4.1.4 on 2022-12-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.CharField(max_length=255),
        ),
    ]
